version: 1


log_directory: logs
default_log_filename: app.log
default_file_format: "%(asctime)s - %(name)-10s - %(levelname)-8s : %(message)s"
default_console_format: "%(asctime)s %(levelname)-8s : %(message)s"